HackYourFuture-CPH/fp-class18

src/server/migrations/20211103214847_categories.js

Databases: Migrations for Categories Table
Fixes #18 
using this npm script:- **npm run db:setup** which is shorthand for running knex migrate:latest followed by knex seed:run
- [X ] I have performed a self-review of my own code
- [X ] I have followed the name conventions for CSS Classnames and filenames, Components names and filenames, Style filenames, if you are in doubt check the the project README.MD and here https://github.com/HackYourFuture-CPH/curriculum/blob/master/review/review-checklist.md
- [ X] I have commented my code, particularly in hard-to-understand areas, if you code was simple enough mark the box anyway
- [X ] I have made corresponding changes to the documentation, if you code was simple enough mark the box anyway
- [ X] This PR is ready to be merged and not breaking …

Databases: Created Migrations for Categories Table

---

src/server/migrations/20211105095000_products-table.js

Databases: Created Migrations for Products Table
Fixes #17 
tested using: npm run knex -- migrate:latest

Databases: Created Migrations for Products Table

---

src/server/seeds/development/products.js

Adding data to work with in Products and Categories tables
Fixes  #50 
MAke sure products and categories migartion tables are available.  run `npm run db:setup` check db for data added

Databases: Create Seeding for Products and Categories Table

---

src/client/containers/404Page/404Page.Container.js
src/client/containers/404Page/404Page.Style.css
src/client/containers/CartPage/CartPage.Container.js
src/client/containers/CartPage/CartPage.Style.css
src/client/containers/CategoryPage/CategoryPage.Container.js
src/client/containers/CategoryPage/CategoryPage.Style.css
src/client/containers/ConfirmationPage/ConfirmationPage.Container.js
src/client/containers/ConfirmationPage/ConfirmationPage.Style.css
src/client/containers/FavoritesPage/FavoritesPage.Container.js
src/client/containers/FavoritesPage/FavoritesPage.Style.css
src/client/containers/LandingPage/LandingPage.Container.js
src/client/containers/LandingPage/LandingPage.Style.css
src/client/containers/MonthlyArrivalsPage/MonthlyArrivalsPage.Container.js
src/client/containers/MonthlyArrivalsPage/MonthlyArrivalsPage.Style.css
src/client/containers/OrderPage/OrderPage.Container.js
src/client/containers/OrderPage/OrderPage.Style.css
src/client/containers/ProductPage/ProductPage.Container.js
src/client/containers/ProductPage/ProductPage.Style.css
src/client/containers/ProfilePage/ProfilePage.Container.js
src/client/containers/ProfilePage/ProfilePage.Style.css

This PR will create the dummy pages according to the issue  Fixes #61
Run the project and make sure that components have empty values. 
Check the issue 61 and be sure that all components are created.

Frontend: dummy Pages Created

---

src/client/components/NumberInput/NumberInput.component.js
src/client/components/NumberInput/NumberInput.stories.js
src/client/components/NumberInput/NumberInput.styles.css

Number Input component to enter product quantity. Can be reused in Product card and Shopping cart item
Fixes #16
Tested with `npm run client` and `npm run storybook`

Storybook: Added NumberInput component

---

src/client/components/Button/Button.component.js
src/client/components/Button/Button.stories.js
src/client/components/Button/Button.styles.css

Added buttons and can add more different types with size and color
Fixes #2 
checked with npm run storybook

Storybook: Button Component

---

src/server/api/controllers/categories.controller.js
src/server/api/routes/api-router.js
src/server/api/routes/categories.router.js

This PR will provide categories info to display category options for user.
Fixes #68 
setup database :`npm run db:setup`, then `npm run dev`
http://localhost:3000/api/categories
Swagger -> http://localhost:3000/api/documentation/#/

Backend: Endpoint to retrieve categories info- GET api/categories

---

src/server/api/controllers/products.controller.js
src/server/api/routes/products.router.js

Gets 'Products' using query by number of days before before created 
Fixes # 75
testing by http://localhost:5000/api/products?daysBeforeToday=30

Backend: Endpoint to show monthly products - GET api/products?daysBeforeToday={number} 

---

src/client/components/ProductView/ProductView.styles.css

Add css styles required by Landing page to match figma

Added styles to fit landing page

---

src/server/migrations/20211118122009_order_items.js

Removed id field from order_items migrations
Fixes #20 
npm run db:setup

Databases: Create Migrations for Order_Items table

---

src/server/seeds/development/03_users.js

Created seeding for users table
Fixes #103 
npm run db:setup

Databases: Created seeding for users table

---

src/client/components/menu/Menu.styles.css

Changed the menu style component
Fixes #8 
npm run storybook

Frontend : Menu Style Updated

---

src/client/components/ProductView/ProductView.component.js

This PR fixes bug found on Landing page. Sometimes after refresh productvew is not rendering products
With landing page merged refersh page to see all products present

Fixed: ProductView sometimes did not show products on refresh

---

src/server/seeds/development/05_orders.js

Created seeding for orders table
Fixes #105 
npm run db:setup

Databases: Created seeding for orders table

---

src/server/seeds/development/04_favorites.js

Created seeding for favorites table
It creates the required data for the favorites table. It contains the favorite products for users.
Fixes #104 
npm run db:setup

Databases: Created seeding for favorites table

---

src/server/seeds/development/06_order_items.js

Created seeding for order_items table
Fixes #105 
using the command: npm run db:setup

Databases: Created seeding for order_items table

---

src/client/components/HeroImage/HeroImage.styles.css

This PR is about fixing hero image css.
Fixes #13 
Please run command -> npm run storybook and you can see hero text is more center on background image.

fixing hero image css

---

__mocks__/fileMock.js
__mocks__/styleMock.js
package.json

This PR will update jest from package.json. Because in Landing or other pages we are getting mock error. Build test is gives error.
Fixes [Page errors](https://github.com/HackYourFuture-CPH/fp-class18/runs/4252715356?check_suite_focus=true) 
Can be tested on Landing Page PR

Package.json update for mock error

---

src/client/components/ProductView/ProductView.component.js
src/client/components/ProductView/ProductView.stories.js
src/client/components/ProductView/ProductView.styles.css

So Pages can pass there own header
Retrun import images because images not shown on heroku

ProductView: Change header to be passed in  props, and return image import

---

src/server/api/controllers/orders.controller.js
src/server/api/routes/api-router.js
src/server/api/routes/orders.router.js

Endpoint to store or save the new order data in the orders table 
Fixes #102 
on swagger api documentation: **http://localhost:3000/api/documentation/** 
we can test 
**GET​/orders** :- Get all orders
**POST/orders** :- **_Save new order information_**
**GET/orders​/{ID}** :- Get order by ID
AND ALSO 
**npm run dev** / **npm run server**

Backend: Endpoint to store a new order for users : POST api/orders

---

src/client/containers/LandingPage/LandingPage.Container.js

This PR will update Landing Page for the carousel Image bug
Fixes [#9](https://github.com/HackYourFuture-CPH/fp-class18/issues/9)
Can be tested with npm run dev

Frontend: Update Landing Page for Carousel

---

src/client/hooks/useAuthentication.js

Skip firebase init in storybook

Skip firebase init in storybook

---

src/server/api/routes/users.router.js

This PR is fixing swagger name of userPatch.
Fixes [#45](https://github.com/HackYourFuture-CPH/fp-class18/issues/45)
Can be test with npm run dev

Backend: Small Fix about User Patch Swagger Name

---

.vscode/settings.json
src/client/App.js
src/client/containers/404Page/404Page.Container.js
src/client/containers/404Page/404Page.Style.css

It displays undefined path as 404 Error page 
Fixes # 151
npm run dev and use undefined path

FrontEnd: 404Page 

---

src/client/components/menu/Menu.component.js

On menu, category links are working and its redirecting to particular page according to link
Fixes # 150
"npm run dev" and select category->lamp

FrontEnd: Change the category page calling in Menu

---

src/client/components/TotalPriceCard/TotalPriceCard.component.js
src/client/components/TotalPriceCard/TotalPriceCard.stories.js
src/client/components/TotalPriceCard/TotalPriceCard.styles.css

Storybook: Total Price Content Card component added
Fixes #59 
Can be tested using: 
`npm run dev` & `npm run storybook`

Storybook: Content Card - TotalPrice

---

src/client/components/ProductDetails/ProductDetails.component.js
src/client/components/ProductDetails/ProductDetails.stories.js
src/client/containers/ProductPage/ProductPage.Container.js

This PR is fixing product details component's image rendering problem
Fixes #10 
Can be tested with npm run dev

Frontend: Fixed productDetails component Image bug

---

src/client/components/Purchases/Purchases.component.js
src/client/components/Purchases/Purchases.stories.js
src/client/components/Purchases/Purchases.styles.css

This component is about the Purchases of the user with order id and date.
Fixes #58
npm run storybook

Storybook: Content Card - Purchases

---

src/client/containers/ProductPage/ProductPage.Container.js

When product is not available ..it has to show NOT FOUND Page. So that we can understand that product user searching is not available..
Fixes # 161
"npm run test" and "localhost://3000/product/45"

FrontEnd: Product Page has to show Not Found Page when given product is not available

---

src/client/App.js
src/client/components/menu/Menu.component.js
src/client/containers/MonthlyArrivalsPage/MonthlyArrivalsPage.Container.js
src/client/containers/MonthlyArrivalsPage/MonthlyArrivalsPage.Style.css

To get monthly arriavals -- (latest products 30 days before)
Fixes #156 
"npm run test" and "localhost://3000/monthly-arrivals"

Frontend: Monthly Arrivals Page

---

src/client/containers/CategoryPage/CategoryPage.Container.js
src/client/containers/CategoryPage/CategoryPage.Style.css

Fixed sorting component styling on the category page.
Fixes #99 
npm run dev

Fix on sorting component styling on Category Page

---

src/client/containers/MonthlyArrivalsPage/MonthlyArrivalsPage.Style.css

There is a css bug on Monthly Arrivals Page 
Fixes # CSS changes on productDetails
npm run dev and see product details page 

FrontEnd: fixed css bug on product details in MonthlyArrivals

---

src/client/components/menu/Menu.component.js

Typo fix in monthly arrivals.
npm run dev

Frontend:Monthly arrivals typo fix

---

.env.example
src/client/firebase/auth.js
src/server/api/controllers/users.controller.js
src/server/api/routes/users.router.js
src/server/migrations/20211102015225_create_users_table.js
src/server/migrations/20211104081529_orders.js
src/server/migrations/20211107144056_favorites.js
src/server/seeds/development/03_users.js
src/server/seeds/development/04_favorites.js
src/server/seeds/development/05_orders.js

THis PR will fix adding firebase user to database. Also provide seeding compatible with firebase user.
Fixes #176 
1. Make sure firebase is set up and working (you have added your firebase API KEY in .env, there is no firebase error in console)
2. clean the previuos database `npm run db:clean`
3. Add TEST_USER_UID to env file from example (if you change it to your working firebase uid it will create seeding for your user)
4. setup new database provided in this branch `npm run db:setup` => You will see 1 test user addded to DB. Orders and favorites are available for that user (check with his id in swagger)
5. run application `npm run dev`
6. login through button in menu => a new user will be added to user table (with your uid in firebase)

Database: Changes to database setup to add user from firebase

---

.github/workflows/migrations.yml

This PR fixes issue with failing PRs due to TEST USER UID is setup in env vars

Added test user id to env vars in github workflow

---

src/client/App.js
src/client/components/ButtonV2/ButtonV2.component.js
src/client/components/ButtonV2/ButtonV2.stories.js
src/client/components/ButtonV2/ButtonV2.styles.css
src/client/components/Loader/Loader.component.js
src/client/components/Loader/Loader.stories.js
src/client/components/Loader/Loader.styles.css
src/client/components/Loader/index.js
src/client/containers/CategoryPage/CategoryPage.Container.js
src/client/containers/CategoryPage/CategoryPage.Style.css
src/client/containers/MonthlyArrivalsPage/MonthlyArrivalsPage.Container.js
src/client/containers/ProductPage/ProductPage.Container.js
src/client/containers/ProductPage/ProductPage.Style.css
src/client/containers/ResetPassword/index.js
src/client/containers/SignIn/index.js
src/client/containers/SignUp/index.js

Button to rediirect to home on category page and product page. So that user can see home button.
Added Loader to render when its loading in category page and product page.
Fixes #180 
"npm run dev" and got to category page where you can see home button (click to go home)

FrontEnd: Home button for category page and product page

---

src/client/containers/CategoryPage/CategoryPage.Container.js
src/client/containers/ProductPage/ProductPage.Container.js

To render the productpage and category page coming by loader when its loading not by 404page
Fixes # 203
npm run dev and refresh fast on productpage and category page

FrontEnd: Loader Issue when rendering productpage and category page

---

src/client/components/ContactForm/ContactForm.component.js
src/client/components/ContactForm/ContactForm.styles.css
src/client/components/DeliveryInfo/DeliveryInfo.component.js
src/client/components/DeliveryInfo/DeliveryInfo.stories.js
src/client/components/DeliveryInfo/DeliveryInfo.styles.css

Css changes for parent page alignment

---

src/client/components/Purchases/Purchases.component.js
src/client/components/Purchases/Purchases.stories.js
src/client/components/Purchases/Purchases.styles.css

Purchases component Style Changes

---

src/client/components/NumberInput/NumberInput.styles.css
src/client/components/ProductDetails/ProductDetails.component.js
src/client/components/ProductDetails/ProductDetails.style.css

This PR is improving product details component for responsive design. Added spans for rechange font size for page css. Added transparent for Number input component.
Fixes #10 
npm run dev product details page

Frontend: Improve Product Details for responsive

---

src/server/api/controllers/users.controller.js
src/server/api/routes/users.router.js

This PR is adding favorite item for user in favorites database
Fixes #193 
Can be test with npm run dev => api/swagger

Backend: EndPoint to create favorites-POST api/users/{:id}/favorites/

---

src/client/components/Auth/AuthenticatedRoute.js
src/client/components/Auth/NonAuthenticatedRoute.js
src/client/firebase/auth.js

This PR fixes `AuthenticatedRoute` keeps redirecting to homepage even when authorised when you reload page url.
Put your page that should go in `AuthenticatedRoute`, when your are logged in type url in browser path => page will load

Added save/delete firebase user to localStorage

---

src/client/components/ProductDetails/ProductDetails.style.css

This PR is improving product Details css file
Fixes #10 
npm run dev

Frontend: Update about product details

---

src/client/App.js
src/client/components/menu/Menu.component.js
src/client/containers/FavoritesPage/FavoritesPage.Container.js
src/client/containers/FavoritesPage/FavoritesPage.Style.css
src/server/api/controllers/users.controller.js
src/server/api/routes/users.router.js

Frontend: Favorites page

---

src/client/containers/ProductPage/ProductPage.Container.js

Create a functionality for explore button
Fixes  #179
On Product detail Page manually.
npm run dev, npm run code:lint

Link explore category button to category page

---

src/client/containers/MonthlyArrivalsPage/MonthlyArrivalsPage.Container.js

Button added to redirect home on Monthly Arrivals Page
npm run dev and http://localhost:3000/monthly-arrivals

Frontend: button to go home in Monthly Arrivals Page

---

src/client/components/ShoppingItem/ShoppingItem.js
src/client/components/ShoppingItem/ShoppingItem.styles.css

edit ShoppingItem Css

---

public/index.html
src/client/.storybook/preview-head.html
src/client/App.js
src/client/components/Paypal/Paypal.component.js
src/client/components/Paypal/Paypal.stories.js

This PR adding Paypal button that can be useed to simulate payment proccess 
Fixes #186 
`npm run storybook` => Paypal component

Payment: adding Paypal component

---

src/client/components/ProductDetails/ProductDetails.component.js
src/client/containers/FavoritesPage/FavoritesPage.Container.js
src/client/containers/MonthlyArrivalsPage/MonthlyArrivalsPage.Container.js

When user click on ADDTOCART button on any product it will show modal 
Fixes #222 
"npm run dev" and press ADDTOCART button on any page

FrontEnd: Modal comes when add to cart click

---

src/server/seeds/development/02_products.js
src/server/seeds/production/02_products.js
src/server/seeds/production/03_users.js
src/server/seeds/production/04_favorites.js
src/server/seeds/production/05_orders.js

Added files from development to production
Changed spell mistake on procucts file.
Fixes #223 
check both staging and production heroku apps

BackEnd: Files added to Production same as Development

---

src/client/components/ProductDetails/ProductDetails.component.js
src/client/components/menu/Menu.component.js
src/client/containers/LandingPage/LandingPage.Container.js
src/client/containers/MonthlyArrivalsPage/MonthlyArrivalsPage.Container.js
src/client/containers/ProductPage/ProductPage.Container.js

Fixes #236 
npm run dev and go to Product page or Monthly Arrivals Page and select icon --> go to favorites ... so you can see added product in favorites

FrontEnd: Favorite icon function Monthly Page and Product Page - adding product to favorites

---

src/client/App.js
src/client/containers/CartPage/CartPage.Container.js

This PR is to use auth in cart page using firebase.
Since base on shopping cart context functionality implemented by Yones, it is clear now that shopping cart will use the local storage for storing the cart items. 
hence a user without login can also add the item in his shopping cart with creating any database entry (in order table).  
I will update the shopping cart functionality in another PR ( getting shopping cart item from localStorage)  
Fixes #226 
npm run dev 
go to cart page  localhost/cart/4
1.  as authenticated user ( it must show your name and email)
2.  if not authenticated, it only show name as "Guest"

adding auth, showing user or guest

---

src/client/components/ShoppingItem/ShoppingItem.js

This PR is about loading images on shopping cart page ( mainly on heroku)  
Fixes #228 
test, on local and heroku, it must load the products images

fixing shopping cart image loading on heroku

---

src/client/components/Modal/Modal.styles.css

This PR is fixing modal component's css.
Fixes #107 
npm run dev

Frontend: Small fix modal css

---

src/client/App.js
src/client/containers/MonthlyArrivalsPage/MonthlyArrivalsPage.Container.js
src/client/containers/ProductPage/ProductPage.Container.js

Guest could not see product: bug fixed
Fixes #236
npm run dev .. as guest without login

FrontEnd: bug fixed for guest productpage

---

src/client/components/DeliveryInfo/DeliveryInfo.styles.css
src/client/components/Purchases/Purchases.styles.css
src/client/containers/OrderPage/OrderPage.Container.js
src/client/containers/OrderPage/OrderPage.Style.css
src/client/containers/ProfilePage/ProfilePage.Container.js
src/client/containers/ProfilePage/ProfilePage.Style.css

Fixing Delivery Information styles and profile page styles
Fixes #243
npm run dev
http://localhost:3003/profile

 Frontend: Delivery info styles and order page styles

---

src/client/App.js
src/client/components/ProductDetails/ProductDetails.component.js
src/client/components/menu/Menu.component.js
src/client/containers/FavoritesPage/FavoritesPage.Container.js
src/server/api/controllers/users.controller.js

Fixed by getting favorites without duplicates. so that I can see the favorites without duplicates on Favorites Page
Fixes #247
Fixes #231 
"npm run dev" and login and add 2 times one product but it wont get two like before

Backend: Bug on getting duplicate favorites which displaying on Favorites Page

---

src/client/components/ProductDetails/ProductDetails.style.css

This PR is fixed css problem in product details component. Some CSS files are affecting this component. So product details is getting some CSS problem. That why I did another fix.
Fixes #10 
npm run dev

FrontEnd: Update For Product Details CSS

---

src/client/App.js
src/client/components/ShoppingItem/ShoppingItem.js
src/client/containers/CartPage/CartPage.Container.js

This PR is about using Shopping context ( localStorage), changing quantity and removing item from cart 
this PR also fix  the keep Shopping button 
Due to non availability of userId in cart page, Deliver Info component has been remove for time being. It will be added in another PR/issue
Fixes #227 
npm run dev
http://localhost:3000/cart
check cart item are loading properly 
you shall be able to change the quantity of item in cart
you shall be able to delete the item from cart 
keep shopping button shall take user to landing page

Cart using shopping context (localStorage)

---

src/client/components/TotalPriceCard/TotalPriceCard.component.js
src/client/components/TotalPriceCard/TotalPriceCard.styles.css
src/client/containers/OrderPage/OrderPage.Style.css

Fix Css in  TotalPrice and order page to display order page according to figma

---

src/client/components/Button/Button.styles.css
src/client/components/ButtonV2/ButtonV2.component.js
src/client/components/ButtonV2/ButtonV2.stories.js
src/client/components/Carousel/Carousel.style.css
src/client/components/ContactForm/ContactForm.styles.css
src/client/components/HeroImage/HeroImage.styles.css
src/client/components/Loader/Loader.styles.css
src/client/components/ProductView/ProductView.styles.css
src/client/components/ShoppingItem/ShoppingItem.styles.css
src/client/components/Sorting/Sorting.styles.css
src/client/components/TotalPriceCard/TotalPriceCard.styles.css
src/client/components/menu/Menu.styles.css
src/client/containers/404Page/404Page.Container.js
src/client/containers/404Page/404Page.Style.css
src/client/containers/CartPage/CartPage.Container.js
src/client/containers/CartPage/CartPage.Style.css
src/client/containers/CategoryPage/CategoryPage.Style.css
src/client/containers/ConfirmationPage/ConfirmationPage.Container.js
src/client/containers/ConfirmationPage/ConfirmationPage.Style.css
src/client/containers/FavoritesPage/FavoritesPage.Container.js
src/client/containers/FavoritesPage/FavoritesPage.Style.css
src/client/containers/LandingPage/LandingPage.Container.js
src/client/containers/LandingPage/LandingPage.Style.css
src/client/containers/MonthlyArrivalsPage/MonthlyArrivalsPage.Container.js
src/client/containers/MonthlyArrivalsPage/MonthlyArrivalsPage.Style.css
src/client/containers/ProfilePage/ProfilePage.Container.js
src/client/containers/ProfilePage/ProfilePage.Style.css

Fixed all components and containers class names. so you can get proper result of css and no unnecessary styles by same name or tag between any components/containers. Added "keep shopping" story button.
Fixes #259 
npm run dev
npm run storybook

FrontEnd: Class Names in front of every component and Container

---

src/server/api/controllers/products.controller.js
src/server/api/routes/products.router.js

Update stock_amout field in products table after payment.
Fixes #142 
localhost:http://localhost:3000/api/documentation

Backend: Update stock amount 

---

src/client/components/menu/Menu.component.js
src/client/components/menu/Menu.styles.css

Cart Icon showing number of items added to it
Fixes #235 
`npm run dev`

Implemented badge on Cart Icon to display the number of items added to the Cart

---

src/client/containers/CartPage/CartPage.Container.js
src/client/containers/OrderPage/OrderPage.Container.js
src/server/api/controllers/orders.controller.js
src/server/api/routes/orders.router.js

Added functionalities to the Shopping Cart Page Buttons (REVIEW ORDER & KEEP SHOPPING) 
#239 
using` npm run dev`

Add functionalities to the Shopping Cart Page Buttons (REVIEW ORDER & KEEP SHOPPING) 

---

src/client/components/menu/Menu.component.js

Calling landing page when clicking logout and login button.
Fixes #261
npm run dev

Frontend:  Login/logout redirection to landing page

---

src/client/App.js
src/client/components/menu/Menu.component.js
src/client/containers/FavoritesPage/FavoritesPage.Container.js
src/client/containers/FavoritesPage/FavoritesPage.Style.css
src/client/containers/MonthlyArrivalsPage/MonthlyArrivalsPage.Container.js

Fixed mobile version of menu component and Favorites authorization. You can access mobile menu properly and favorites only for authorized user with rendering only his data...
Fixes #256 #261 
npm run dev
check wheather menu closes by itself on mobile mode
Try to render favorites of another user

Bug FrontEnd: Bugs on mobile menu And Favorites Authorization

---

src/client/components/menu/Menu.component.js
src/client/context/shoppingCart/ShoppingCartProvider.js
src/client/firebase/auth.js

Added clear  shopping Cart from local storage on logout
Fixes #  shopping Cart in local storage on logout

Added clear  shopping Cart from local storage on logout

---

public/index.html
src/client/App.js
src/client/components/Paypal/Paypal.component.js
src/client/containers/CartPage/CartPage.Container.js
src/client/containers/ConfirmationPage/ConfirmationPage.Container.js
src/client/containers/OrderPage/OrderPage.Container.js
src/server/api/controllers/orders.controller.js
src/server/api/routes/orders.router.js

After clicking Paypal button on Order review Page user will be redirected to a window with payment system and on Success to order Confirmation page. Order status is chanegd to payed in DB
Additionaly added:
1. api route to change order status: PATCH api/orders
2. authorisation on OrdersPage - user can only see his orders
3. payment button will not show if order status is not payed
Fixes #216 
`npm run dev` => create order => click paypal button => Login to payment with test user (ask me)

Frontend: Added payment button and redirect to order confirmation

---

src/client/components/ContactForm/ContactForm.styles.css
src/client/components/ShoppingItem/ShoppingItem.styles.css
src/client/components/TotalPriceCard/TotalPriceCard.component.js
src/client/components/TotalPriceCard/TotalPriceCard.styles.css
src/client/containers/CartPage/CartPage.Style.css
src/client/containers/OrderPage/OrderPage.Style.css
src/client/containers/ProfilePage/ProfilePage.Style.css

This PR is updating shopping product component, shopping cart page and order page for responsive design. 
Fixes #24 #101 #93 
npm run dev =>  /cart  and  /order/1

Frontend: Shopping Cart and Order Page Responsive Design

---

src/client/components/Purchases/Purchases.styles.css
src/client/containers/ProfilePage/ProfilePage.Style.css

This is about Profile page styles and responsive
Fixes #243
npm run dev

Frontend: Profile page styles and responsive

---

src/client/components/Sorting/Sorting.styles.css

Background color for the categories options on the SortBy is changed to the web app theme color : violet 
Issue #283 
usnig `npm run dev`

Frontend: Change color based on the site theme & fill color on entire field for Category option on SortBy

---

src/client/components/Carousel/Carousel.style.css
src/client/components/ProductDetails/ProductDetails.style.css
src/client/components/menu/Menu.component.js
src/client/components/menu/Menu.styles.css
src/client/containers/OrderPage/OrderPage.Container.js

This PR makes the Menu bar sticky so when we scroll down we can always access it
Fixes #276 
npm run dev
check menu bar is now sticky...

FrontEnd: Make the Menu bar sticky so when we scroll down we can always access it

---

src/client/components/ProductsPagination/ProductsPagination.styles.css

Changed the background color of the pagination buttons to app theme color
Issue #294 
`npm run dev`

Frontend/improvement: Change the background color of the pagination buttons to the web app theme color: violet

---

src/client/components/Carousel/Carousel.style.css
src/client/components/ProductDetails/ProductDetails.style.css
src/client/components/Purchases/Purchases.styles.css
src/client/components/ShoppingItem/ShoppingItem.js
src/client/components/Sorting/Sorting.styles.css
src/client/components/menu/Menu.component.js
src/client/components/menu/Menu.styles.css
src/client/containers/CartPage/CartPage.Container.js
src/client/containers/ProfilePage/ProfilePage.Style.css

This PR is removing 'review order' button from cart page if cart page is empty
Fixes #272 
npm run dev => Test with empty shopping cart

Bug : Fix review button when shopping cart empty and if user is not login redirect user for login from review order button

---

src/server/api/controllers/products.controller.js

Fix on ZERO stock amount
Fixes #290 
npm run dev

Frontend: Fix stock amount for already added Zero value

---

src/client/components/Purchases/Purchases.component.js
src/client/components/Purchases/Purchases.stories.js
src/client/components/Purchases/Purchases.styles.css
src/client/containers/ProfilePage/ProfilePage.Container.js

This PR reverts the merged PR #275 , since it have some issues and the cart page and my account page is not loading
_**Screenshot after i tested:**_ 
**_Screenshot_ after Daniel tested:_**
When we test on staging there is error, the screenshots of the error are below:
got to https://staging-webshop-class18-fp.herokuapp.com/ and test by creating new order, it doesnot navigate to the cart page and also it do not load the My Account page.

Revert "Bug: Not showing the orders on my profile page once I finish the payment"

---

src/client/App.js
src/client/components/ProductDetails/ProductDetails.component.js
src/client/components/menu/Menu.component.js
src/client/components/menu/Menu.styles.css
src/client/containers/FavoritesPage/FavoritesPage.Container.js
src/client/containers/MonthlyArrivalsPage/MonthlyArrivalsPage.Container.js
src/client/containers/ProductPage/ProductPage.Container.js

This PR will remove heart if you are not logged in 
Fixes #270 
npm run dev 
check logged in and logged out

FrontEnd: Removed heart if you are not logged in on Menu, Monthly Arrivals and Product Page
